# checks if there is a project description signed by this address
PREFIX regenregistry: <https://registry.regen.network/schema#>
ASK {
    GRAPH $eventDoc {
        ?x a regenregistry:ProjectDescription .
        ?x regenregistry:projectId $projectId
    }
}

# $projectId = <regen:eco/projects/10>
# $projectDeveloper = <regen:acc/regenabcdef1234567ghjkl>
