# checks if there is a project description signed by this address
PREFIX regenregistry: <https://registry.regen.network/schema#>
ASK {
    GRAPH $eventDoc {
        regenregistry:root a regenregistry:ProjectDescription .
        regenregistry:root regenregistry:projectId <regen:eco/projects/10>
    }
}

# $projectId = <regen:eco/projects/10>
# $projectDeveloper = <regen:acc/regenabcdef1234567ghjkl>
